name = "embeng"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true
[[routes]]
pattern = "embeng.ggff.net"
custom_domain = true

[vars]
PROXYIP = "103.133.223.51:2096"
UUID = "218bc9a3-00dc-4ba9-8539-5676b54631e7"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
